pipeline:

  my-build:
    image: docker:17.12.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t developer-induction .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.12.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+developer_induction" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag developer-induction quay.io/ukhomeofficedigital/developer-induction:$${DRONE_COMMIT_SHA}
      - docker tag developer-induction quay.io/ukhomeofficedigital/developer-induction:latest
      - docker push quay.io/ukhomeofficedigital/developer-induction:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/developer-induction:latest
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    secrets:
      - kube_token
    environment:
      - KUBE_SERVER=https://kube-dev.dsp.notprod.homeoffice.gov.uk
      - KUBE_NAMESPACE=dev-induction
      - INSECURE_SKIP_TLS_VERIFY=true
    commands:
      - cd kube
      - kd -f deployment.yml -f ingress.yml -f service.yml
    when:
      event: [deployment, push]
      branch: master
